#BurgerNama POS Configuration
#Sun Mar 29 15:24:49 IST 2026
tax.sgst=0.09
restaurant.name=BurgerWala
restaurant.tagline=Asli Swad, Har Baar\!
currency.symbol=\u20B9
restaurant.address=MG Road, Bengaluru - 560001
tax.cgst=0.09
admin.pin=1234
restaurant.gstin=27AABCS1429B1Z1
